name = "maskRCNN"
uuid = "322e080d-18ba-4a06-9184-275d3691eaec"
authors = ["Sven Duve"]
version = "1.0.0-DEV"

[compat]
julia = "1.9.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
